### ISSUE TITLE
Feature: Include sheet opens

### ISSUE THREAD

**Issue by alexometis** [kongson-cheung/qlik-saas-application#5]
With the new sheet open audit entry, it makes sense to add this in, so updating the APP_OBJECT_LOG script and App Object sheet to match `'com.qlik.v1.analytics.analytics-app-client.sheet-view.opened'` as well as the existing `
'com.qlik.app.object.created', 'com.qlik.app.object.deleted', 'com.qlik.app.object.published', 'com.qlik.app.object.unpublished', 'com.qlik.app.object.updated'`

I also tweaked the APP_OBJECT_LOG script to capture a couple more fields from this event type to line up with the existing:
```
    coalesce(objectId_u1,sheetId_u1) as [App Object ID],
    if([eventType]='com.qlik.v1.analytics.analytics-app-client.sheet-view.opened','sheet',objectType_u1) as [App Object Type]
```

**Comment by kongson-cheung** [comment]
Added in 2024-10-22 version.
